#!/usr/bin/env python3
"""Write the demo school as a MySQL dump (``database/seed_data.sql``).

The script seeds a throwaway in-memory SQLite database with exactly the data
``scripts/seed_data.py`` produces, then writes every row out as MySQL
``INSERT`` statements in foreign-key order.  Timestamps are pinned to the
start of the academic year so the output is byte-for-byte reproducible for a
given seed, year and Faker version.

The dump contains data only.  Load ``database/schema.sql`` first::

    mysql -u root -p < database/schema.sql
    mysql -u root -p school_db < database/seed_data.sql

Usage::

    python scripts/export_seed_sql.py
    python scripts/export_seed_sql.py --output /tmp/seed.sql --seed 99
"""

from __future__ import annotations

import argparse
import logging
import sys
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path
from typing import Iterable, List, Sequence

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

import seed_data  # noqa: E402
from sqlalchemy import select  # noqa: E402

from app import create_app  # noqa: E402
from app.extensions import db  # noqa: E402
from app.models import (  # noqa: E402
    AcademicYear,
    ClassSubject,
    Exam,
    Mark,
    SchoolClass,
    Section,
    Student,
    Subject,
)

#: Tables in the order they must be inserted to satisfy the foreign keys.
MODELS = (AcademicYear, SchoolClass, Section, Subject, ClassSubject, Exam, Student, Mark)

#: Rows per multi-row INSERT statement.
BATCH_SIZE = 500

DEFAULT_OUTPUT = ROOT / "database" / "seed_data.sql"


def sql_literal(value: object) -> str:
    """Render a Python value as a MySQL literal."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, Decimal)):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, datetime):
        return f"'{value:%Y-%m-%d %H:%M:%S}'"
    if isinstance(value, date):
        return f"'{value:%Y-%m-%d}'"
    text = str(value).replace("\\", "\\\\").replace("'", "''").replace("\n", "\\n")
    return f"'{text}'"


def insert_statements(table: str, columns: Sequence[str], rows: Iterable[Sequence[object]]) -> List[str]:
    """Build batched ``INSERT`` statements for one table."""
    rows = list(rows)
    column_list = ", ".join(f"`{name}`" for name in columns)
    statements = []
    for start in range(0, len(rows), BATCH_SIZE):
        values = ",\n".join(
            "(" + ", ".join(sql_literal(value) for value in row) + ")"
            for row in rows[start : start + BATCH_SIZE]
        )
        statements.append(f"INSERT INTO `{table}` ({column_list}) VALUES\n{values};")
    return statements


def build_dump(seed: int, year_label: str) -> str:
    """Seed an in-memory database and return the dump text."""
    app = create_app(
        "development",
        {"SQLALCHEMY_DATABASE_URI": "sqlite://", "SQLALCHEMY_ENGINE_OPTIONS": {}, "SQLALCHEMY_ECHO": False},
    )
    start_year = int(year_label.split("-")[0])
    pinned = datetime(start_year, 4, 1, 9, 0, 0)

    with app.app_context():
        db.create_all()
        seed_data.seed_database(seed, year_label)
        db.session.commit()

        counts = {}
        sections: List[str] = []
        for model in MODELS:
            table = model.__table__
            columns = [column.name for column in table.columns]
            result = db.session.execute(select(table).order_by(table.c.id)).all()
            rows = [
                [pinned if name in ("created_at", "updated_at") else row._mapping[name] for name in columns]
                for row in result
            ]
            counts[table.name] = len(rows)
            sections.append(f"-- {table.name}: {len(rows)} rows")
            sections.extend(insert_statements(table.name, columns, rows))
            sections.append("")

    import faker

    header = [
        "-- ---------------------------------------------------------------------------",
        "-- school_db - fictional demo data for Greenfield Public School",
        "--",
        "-- Generated by scripts/export_seed_sql.py; do not edit by hand.",
        f"--   seed={seed}  academic_year={year_label}  Faker={faker.VERSION}",
        "--   " + ", ".join(f"{name}={count}" for name, count in counts.items()),
        "--",
        "-- Every name, address, phone number and mark is invented.",
        "--",
        "-- Load the schema first, then this file. Existing rows in these tables are",
        "-- deleted, so the import always leaves exactly the demo school behind:",
        "--   mysql -u root -p < database/schema.sql",
        "--   mysql -u root -p school_db < database/seed_data.sql",
        "-- ---------------------------------------------------------------------------",
        "",
        "SET NAMES utf8mb4;",
        "SET FOREIGN_KEY_CHECKS = 0;",
        "SET UNIQUE_CHECKS = 0;",
        "",
        "START TRANSACTION;",
        "",
    ]
    header += [f"DELETE FROM `{model.__tablename__}`;" for model in reversed(MODELS)]
    header.append("")
    footer = ["COMMIT;", "", "SET UNIQUE_CHECKS = 1;", "SET FOREIGN_KEY_CHECKS = 1;", ""]
    return "\n".join(header + sections + footer)


def main(argv: List[str] | None = None) -> int:
    """Write the dump and report where it went."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--seed", type=int, default=seed_data.DEFAULT_SEED)
    parser.add_argument("--year", default=seed_data.DEFAULT_YEAR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.WARNING)
    logging.getLogger().setLevel(logging.WARNING)

    text = build_dump(args.seed, args.year)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {args.output} ({args.output.stat().st_size / 1024:.0f} KiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
